### ISSUE TITLE
出现服务器内部错误(500)

### ISSUE THREAD

**Issue by dora-admin001** [justsweetpotato/potato-search#5]
第一次在测试搜书的时候发现的，小白默默提供支援，大佬加油！
[image](https://user-images.githubusercontent.com/67258691/85482686-f9283c00-b5f5-11ea-9099-29e798e327b0.png)

**Comment by justsweetpotato** [comment]
> 第一次在测试搜书的时候发现的，小白默默提供支援，大佬加油！
> [image](https://user-images.githubusercontent.com/67258691/85482686-f9283c00-b5f5-11ea-9099-29e798e327b0.png)

谢谢反馈！已经修复了，原因是某些网站禁止爬虫，所以 content 取不到内容导致程序错误，Google API 并没有做任何处理，现在我已经加上了错误信息就不会在导致服务器错误了。（其实早就发现这个 BUG，一直懒得修复😢）
感谢你的支持哦，真的给了我很大鼓励❤。
祝你生活愉快，事业顺利。
