### ISSUE TITLE
服务器故障

### ISSUE THREAD

**Issue by ShineShenCn** [justsweetpotato/potato-search#6]
![image](https://user-images.githubusercontent.com/52003087/87131180-9e196900-c2c6-11ea-829d-b3ea271cf505.png)

**Comment by justsweetpotato** [comment]
目前只有一台服务器跑这个程序，有时候在测试服务器，或者在更新代码，就会导致这样。
等我有闲钱了升级服务器🤣，配置负载均衡后就不会再出现服务器宕机的情况了。

感谢你的支持和反馈，祝你生活愉快，事业顺利。
